# Generated by Django 3.0.6 on 2020-05-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('text', models.CharField(max_length=90)),
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
